# Generated by Django 5.1.1 on 2024-09-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_joshshop_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='joshShop',
            new_name='joshItem',
        ),
    ]
